type: Leaf
implementation: state machine
name: Lamp
inputs: [on off intensity]
outputs: []
states:
  turnedoff
  machine turnedon
transitions: 
  from off on in: next on
  from on on in: next off

machine turnedon
states:
  low entry: setlamp('low')
  medium entry: setlamp('medium")
  high entry: setlamp('high')
transitions: 
  default: next low
  from low on intensity: next medium
  from medium on intensity: next high
  from high on intensity: next low
